import React from 'react';
import './aboutus.css'
class AboutUs extends React.Component
{
    constructor(props)
    {
        super(props);
    }

    render()
    {
        return(
            <div>
                <div className="bgimg">
                <div class="header">
                <h1>JOIN WITH OUR TEAM</h1><hr/>
                </div><br/><br/>
                <p>The largest source of climate pollution in the India? Transportation. To solve the climate crisis,
                     we need to make the vehicles on our roads as clean as possible. We have only a decade left to 
                     change the way we use energy to avoid the worst impacts of climate change.
                  Emissions from cars and trucks are not only bad for our planet, they’re bad for our health. 
                  Air pollutants from gasoline- and diesel-powered vehicles cause asthma, bronchitis, cancer, and premature death.
                  The long-term health impacts of localized air pollution last a lifetime, with the effects 
                  borne out in asthma attacks, lung damage, and heart conditions.</p>
                  <p>
                  The electricity that charges and fuels battery electric and plug-in hybrid vehicles comes from power grids, 
                  which rely on a range of sources — from fossil fuels to clean renewable energy.
                Energy grids can vary from one state to another, which means that the carbon footprint of driving an electric
                 vehicle ranges depending on the source of its electricity.
                Earthjustice attorneys are working across the country to bring 100% clean energy, but on our way there
                 (consumption of renewable energy recently surpassed coal), a portion of the electricity in this country 
                 will continue to be generated by the burning of fossil fuels.
                The very good news? Because electric vehicles are more efficient in converting energy to power cars and trucks, 
                electricity across the board is cleaner and cheaper as a fuel for vehicles, even when that electricity comes from the dirtiest grid.
                  </p><br/><br/>
                  <h3>EV concenpt is now accepted and initiated by goverment as well. Goverment is also approaching automobile industries
                      to take part in making of EV's.
                  </h3><br/><br/><br/><br/><br/><br/>
            </div>
        </div>    
        );
    }
}
export default AboutUs;